#SPDX-License-Identifier: MIT-0
---
# tasks file for sample-role
- name: print msg
  debug:
     msg: "this is role task"


- name: print msg
  debug:
     msg: "{{text}}"


- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'     


- name: install apache2
  package:
    name: "{{pkg}}"
    state: present
    

- name: copy index.html
  copy: 
    src: index.html
    dest: /var/www/html/index.html




